### ISSUE TITLE
SyntaxError: node_modules/react-native-input-scroll-view/index.js: Rest element must be last element

### ISSUE THREAD

**Issue by ldco2016** [baijunjie/react-native-input-scroll-view#58]
When I try running: `react-native bundle --entry-file ./index.js --platform ios --bundle-output ios/main.jsbundle --verbose`

I get this error:

```
Loading dependency graph, done.
error SyntaxError: /Users/danale/Projects/engage-application.mobile/node_modules/react-native-input-scroll-view/index.js: Rest element must be last element (108:25)

  106 |             children,
  107 |             useAnimatedScrollView,
> 108 |             ...otherProps,
      |                          ^
  109 |         } = this.props;
  110 |
  111 |         const {
debug SyntaxError: /Users/danale/Projects/engage-application.mobile/node_modules/react-native-input-scroll-view/index.js: Rest element must be last element (108:25)

  106 |             children,
  107 |             useAnimatedScrollView,
> 108 |             ...otherProps,
      |                          ^
  109 |         } = this.props;
  110 |
  111 |         const {
    at Object.raise (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:6344:17)
    at Object.raiseRestNotLast (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:8105:10)
    at Object.checkCommaAfterRest (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:8094:12)
    at Object.parseObjectMember (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:9180:14)
    at Object.parseObj (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:9138:25)
    at Object.parseBindingAtom (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:7945:21)
    at Object.parseVarId (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:10464:20)
    at Object.parseVarId (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:2597:11)
    at Object.parseVar (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:10436:12)
    at Object.parseVarStatement (/Users/danale/Projects/engage-application.mobile/node_modules/@babel/parser/lib/index.js:10258:10)
```

I don't understand what is going on. I created a mock application with all the same dependencies and I have no problems.

**Comment by baijunjie** [comment]
@ldco2016 HI, it doesn't look like it's the latest version?
